### ISSUE TITLE
上传大文件报错

### ISSUE THREAD

**Issue by zfang1995** [chenxingk/AliYunPan#20]
09:05:53.560 [pool-1-thread-4] INFO  xin.xingk.www.util.UIUtil :50 - [2022-11-09 09:05:53] 开始上传：F:\下载\Romance.Of.Three.Kingdom.XIV.With.PowerUp.Kit.v1.0.8.zip
09:05:54.438 [pool-1-thread-4] INFO  xin.xingk.www.util.UIUtil :50 - [2022-11-09 09:05:54] 文件上传，请求状态码：400
09:05:54.456 [pool-1-thread-4] INFO  xin.xingk.www.util.UIUtil :50 - [2022-11-09 09:05:54] 遇到异常情况：java.lang.NullPointerException
	at xin.xingk.www.util.BackupUtil.doUploadFile(BackupUtil.java:186)
	at xin.xingk.www.util.BackupUtil.uploadFileList(BackupUtil.java:146)
	at xin.xingk.www.util.BackupUtil.scanFolders(BackupUtil.java:98)
	at xin.xingk.www.util.BackupUtil.backupTask(BackupUtil.java:64)
	at xin.xingk.www.util.BackupUtil.startBackup(BackupUtil.java:46)
	at xin.xingk.www.ui.Home.lambda$null$3(Home.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by lagogo01** [comment]
和大文件没关系，我上传3兆的小照片一样报这个错
